### ISSUE TITLE
XML Schema Implementation of Geographic Information Metadata documented in ISO/TS 19139-1:2019

### ISSUE THREAD

**Issue by teo89** [ISO-TC211/schemas#3]
I got the license for the ISO/TS 19139-1:2019, but in the document there are not specifications for the new format of the XML schema or which parts of it is changed. Could you please tell me, if there is an XML schema file or a UML for this ISO. If not, when is planned to be published?

**Comment by PeterParslow** [comment]
Having re-read ISO/TS 19139-1:2019, after being part of the project team, I'd say a couple of things:
1. as per the introduction, "this document provides a definitive set of rules for encoding ISO metadata standards in" XML.

The XML schemas that implement those rules are associated with the relevant standards, in particular ISO 19115-3 and ISO 19157-2 - others are expected to come along.

2. 19139 doesn't introduce any namespace for which there would be a normative XSD

3. Clause 7.3.8 describes "Encoding of externally identified implementations", such as Date

We considered including XSD fragments for these "most reused" parts, but reckoned that those actually belong in the standards which define those classes. And looking at the example of Date, an issue was raised in Maribor that it isn't handled consistently across TC211 standards - so amending 19103 to point to an XSD may be premature. 19107 Point already has 19136; 19103 CharacterString is a simple rule, rather than an XSD; PT_FreeText currently has its home in 19115-1.

4. It also contains Clause 8: 

"In order to maximise use of existing approaches and technologies, some classes are specifically encoded using relevant implementations from ISO or other organizations. These encodings are available at http://standards .iso .org/iso/19139/resources." 

At present, that URL leads to a small collection of code lists encoded as CT_CodelistCatalogue, with no namespace declarations.

So overall, I don't think there are any XSDs for 19139-1

**Comment by teo89** [comment]
Thank you for your detailed answer. If I understand correctly from your answer an update of gmd.xsd (Geographic MetaData (GMD) extensible markup language is a component of the XML Schema Implementation of Geographic Information Metadata documented in ISO/TS 19139:2007. GMD includes all the definitions of http://www.isotc211.org/2005/gmd namespace. The root document of this namespace is the file gmd.xsd.) is not planned. If anyone wants to use the MD_Metadata and be conformed with ISO/TS 19139-1:2019 should use the 19115-3 mdb.xsd as referred under the section 9.3.3 
"The MD_Metadata class is included in the Metadata Base (mdb) namespace, which imports the abstract _LineageInformation class from the Metadata for Common Classes (mcc) namespace.".

**Comment by PeterParslow** [comment]
Sort of - no update of gmd.xsd is planned; it has been superceded by mdb.xsd when ISO 19115-3 superceded the XML schemas within ISO 19139:2007.

"If anyone wants to use the MD_Metadata" they will find it in ISO 19115-3 https://standards.iso.org/iso/19115/-3/mdb/2.0/metadataBase.xsd

"If anyone wants to use the MD_Metadata _and be conformed with ISO/TS 19139-2:2019_", then they would be repeating the work done to produce ISO 19115-3.

The idea of publishing the rules is that they are common between the XML implementations of 19115-1 and 19157-1, and will hopefully be used in future on 19110, 19135 - and could be used by anyone else.

This discussion has highlighted a few things for me:
a) the standardisation target of ISO 19139-1:2019, expressed in the introduction, could be improved. It currently says "The standardization target of this document is XML implementations of metadata." and that should really be "XML Schema implementations".

b) the Introduction of 19115-3 attempts to explain this, but taking into account the different dates of publication:

"ISO 19115-1 and ISO 19115-2 define conceptual models for metadata content that are independent of any particular encoding scheme. ISO/TS 19139 and ISO/TS 19139-2 define eXtensible Markup Language (XML) schemas for encoding that content. This document defines XML encodings for ISO 19115-1 and ISO 19115-2 metadata content. This integrated schema makes it possible to use concepts from ISO 19115-1 and ISO 19115-2 together in metadata instance documents, effectively replacing ISO/TS 19139 and ISO/TS 19139-2 and enables automated validation and interchange of ISO 19115-1 and ISO 19115-2, metadata content using standard software tools."

Perhaps the supercession statement in the Foreward to ISO 19139-1:2019 could be improved to make it clear that ISO 19115-3 had already supeceded parts of ISO 19139:2007.
