### ISSUE TITLE
Environmental record elements #1

### ISSUE THREAD

**Issue by enricoboldrini** [ISO-TC211/schemas#47]
Hello,

according to the spec these elements:

          <element name="averageAirTemperature" type="gco:Real_PropertyType"/>
          <element name="maxRelativeHumidity" type="gco:Real_PropertyType"/>
          <element name="maxAltitude" type="gco:Real_PropertyType"/>
          <element name="meterologicalConditions" type="gco:CharacterString_PropertyType"/>
          <element name="solarAzimuth" type="gco:Real_PropertyType"/>
          <element name="solarElevation" type="gco:Real_PropertyType"/>    

in MI_EnvironmentalRecord_Type should be optional; as such it seems they should have minOccurs="0" attribute.

Kind regards,
Enrico

**Comment by ejbleys** [comment]
Ready for review and approval

Thank you, this issue is now being addressed but only in version 2.0
As the elements that are there where mandatory in 19115-3:mac version 1.0 and gmi both derived from (19115-2:2009)

E
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***
