### ISSUE TITLE
Environmental record elements #2

### ISSUE THREAD

**Issue by enricoboldrini** [ISO-TC211/schemas#48]
Hello,

it seems that these elements:

          <element name="averageAirTemperature" type="gco:Real_PropertyType"/>
          <element name="maxRelativeHumidity" type="gco:Real_PropertyType"/>
          <element name="maxAltitude" type="gco:Real_PropertyType"/>

in MI_EnvironmentalRecord_Type lack units of measure from their definitions, but the type is gco:Real... maybe it could be useful to:
1) refine the definition
or
2) use gco:Measure

Kind regards,
Enrico

**Comment by ejbleys** [comment]
Please report this into the TC211 standards Tracker so that it can be considered at the next major TC211 meeting
https://github.com/ISO-TC211/StandardsTracker 

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***
